branch-defaults:
  master:
    environment: einstein-prd
    group_suffix: null
  megaphonely:
    environment: einstein-prd
global:
  application_name: einstein
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
